/* Sahaay - every visible string, in both languages.
 * Contract: 00-CONTRACTS.md §7. window.STRINGS.en and window.STRINGS.hi must
 * carry identical key sets. No sentence may live anywhere else in the code.
 * Placeholders are {braces}; App.t(key, vars) fills them.
 */
window.STRINGS = {
  en: {
    /* ---- navigation ---- */
    "nav.brand": "Sahaay",
    "nav.ministry": "Ministry of Social Justice & Empowerment",
    "nav.home": "Home",
    "nav.schemes": "Schemes",
    "nav.assistant": "Assistant",
    "nav.profile": "Profile",
    "nav.wizard": "Find my scheme",
    "nav.match": "My matches",
    "nav.login": "Sign in",
    "nav.logout": "Sign out",
    "nav.signedInAs": "Signed in as {name}",

    /* ---- language ---- */
    "lang.toggle": "हिं | EN",
    "lang.switched": "Language changed to English.",

    /* ---- shared ---- */
    "common.loading": "Loading…",
    "common.retry": "Try again",
    "common.save": "Save",
    "common.saving": "Saving…",
    "common.saved": "Saved.",
    "common.back": "Back",
    "common.next": "Next",
    "common.finish": "Finish",
    "common.print": "Print",
    "common.view": "View details",
    "common.na": "Not available",
    "common.yes": "Yes",
    "common.no": "No",
    "common.months": "{n} months",
    "common.percent": "{n}%",
    "common.source": "Terms as published at nsfdc.nic.in/scheme",

    /* ---- errors ---- */
    "err.network": "Could not reach the server. Check that it is running, then try again.",
    "err.server": "The server could not answer that request.",
    "err.auth": "Please sign in again.",
    "err.notfound": "That was not found.",
    "err.unknown": "Something did not work. Try again.",

    /* ---- login ---- */
    "login.submit": "Sign in",
    "login.submitting": "Signing in…",
    "login.errorInvalid": "That username and password did not match. Try sunita / demo123.",
    "login.errorNetwork": "Could not reach the server. Check that it is running, then try again.",
    "login.welcome": "Signed in as {name}.",

    /* ---- profile ---- */
    "profile.loadError": "Your saved profile could not be loaded.",
    "profile.saved": "Saved.",
    "profile.saveError": "Your profile could not be saved.",
    "profile.completeness": "Profile complete: {done} of {total} fields",
    "profile.photoUploading": "Uploading the photo…",
    "profile.photoError": "The photo could not be uploaded.",
    "profile.seeMatches": "See my matches →",
    "profile.notifyUnavailable": "The message preview is not available right now.",
    "profile.notifyTo": "Would be sent by {channel} to {to}",
    "profile.needLogin": "Sign in to save a profile.",

    /* ---- field names: profile, wizard, why-panel ---- */
    "field.name": "Name",
    "field.age": "Age",
    "field.is_sc": "Scheduled Caste",
    "field.category": "Category",
    "field.is_woman": "Woman",
    "field.state": "State",
    "field.district": "District",
    "field.email": "Email",
    "field.mobile": "Mobile number",
    "field.purpose": "What the money is for",
    "field.sector": "Kind of work",
    "field.activity_text": "In your own words",
    "field.amount_inr": "Amount needed",
    "field.annual_family_income_inr": "Annual family income",
    "field.education": "Education",
    "field.has_caste_certificate": "Caste certificate",
    "field.has_income_certificate": "Income certificate",
    "field.photo": "Photo",

    /* ---- option labels ---- */
    "category.sc": "Scheduled Caste",
    "category.st": "Scheduled Tribe",
    "category.obc": "Other Backward Class",
    "category.general": "General",
    "purpose.enterprise": "A business",
    "purpose.education": "Education",
    "sector.tailoring": "Tailoring",
    "sector.shop": "Shop",
    "sector.transport": "Transport",
    "sector.agri_allied": "Farming and allied work",
    "sector.services": "Services",
    "sector.manufacturing": "Manufacturing",
    "sector.plantation": "Plantation",
    "sector.construction": "Construction",
    "sector.other": "Something else",
    "education.illiterate": "Did not attend school",
    "education.primary": "Primary",
    "education.middle": "Middle (eighth)",
    "education.matric": "Matriculation (tenth)",
    "education.higher_secondary": "Higher secondary (twelfth)",
    "education.graduate": "Graduate",

    /* ---- catalogue ---- */
    "schemes.count": "Showing {shown} of {total}",
    "schemes.empty": "No scheme matches that search.",
    "schemes.loadError": "The scheme list could not be loaded.",
    "schemes.filterAll": "All",
    "schemes.max": "max {amount}",
    "schemes.closedNote": "No longer open to new applications",
    "cat.loan": "Loan",
    "cat.education": "Education",
    "cat.subsidy": "Subsidy",
    "cat.training": "Training",
    "cat.marketing": "Marketing",
    "status.open": "Open",
    "status.informational": "Information only",
    "status.closed": "Closed to new applications",

    /* ---- one scheme ---- */
    "scheme.loadError": "This scheme could not be loaded.",
    "scheme.notFound": "No scheme was named in the address.",
    "scheme.check": "Am I eligible?",
    "scheme.checking": "Checking against the published rules…",
    "scheme.checkYes": "Yes — you qualify for {scheme}.",
    "scheme.checkYesCost": "{rate} · loan {loan} · instalment {instalment}, {count} of them",
    "scheme.checkNo": "Not yet — {reason}",
    "scheme.checkNoUnblock": "What would change it: {unblock}",
    "scheme.checkIneligible": "Your saved profile does not qualify for this scheme.",
    "scheme.checkInfoOnly": "We hold information for this scheme, but not the rules to check you against it.",
    "scheme.checkNeedProfile": "Answer six questions and we will check this for you.",
    "scheme.checkError": "The check could not be run.",
    "scheme.rateLabel": "Interest rate",
    "scheme.maxLabel": "Maximum amount",
    "scheme.tenureLabel": "Repayment period",
    "scheme.moratoriumLabel": "Moratorium",

    /* ---- matches ---- */
    "match.needProfile": "We need your details first.",
    "match.loading": "Checking every scheme against your details…",
    "match.error": "Your matches could not be worked out.",
    "match.none": "No scheme fits these details yet.",
    "match.topTitle": "Your match: {scheme}",
    "match.rateLine": "{rate} — the lowest rate you qualify for",
    "match.otherRateLine": "{rate} interest",
    "match.loanLine": "Loan {loan} of a {project} project · your share {own}",
    "match.costTitle": "What it costs",
    "match.costInstalment": "Instalment",
    "match.costCount": "Number of instalments",
    "match.costMoratorium": "Moratorium",
    "match.costTotalInterest": "Total interest",
    "match.costTotalRepayment": "Total repayment",
    "match.costRate": "Interest rate",
    "match.freq.quarterly": "every quarter",
    "match.freq.half_yearly": "every six months",
    "match.nearmissTitle": "Close, but not yet",
    "match.nearmissNotYet": "{scheme} — not yet",
    "match.othersTitle": "Also open to you",
    "match.doorTitle": "Where to go",
    "match.doorNone": "No office in your state is listed for this scheme.",
    "match.doorDistance": "{km} km away",
    "match.doorDistanceUnknown": "Distance not known",
    "match.doorRate": "{rate} for you",
    "match.wrongdoorTitle": "Choosing the right office saves you {amount}",
    "match.wrongdoorBody": "The same project costs {bestRate} at {bestName} and {worstRate} at {worstName}, over the same period.",
    "match.whyTitle": "Why this answer?",
    "match.whyLine": "{scheme} · {rule}: {result}",
    "match.whySaw": "we read {value}",
    "match.whyNeeds": "the rule asks for {threshold}",
    "match.printPacket": "Print my packet",
    "match.packetOpening": "Preparing your packet…",
    "match.packetError": "The packet could not be prepared.",

    /* ---- utilisation bands ---- */
    "band.strong": "This state used its full NSFDC allocation in 2025-26.",
    "band.ok": "This state used most of its NSFDC allocation in 2025-26.",
    "band.slow": "This state used less than half of its allocation in 2025-26.",
    "band.weak": "This state used very little of its allocation in 2025-26.",
    "band.none": "No utilisation figure is published for this state.",
    "band.source": "NSFDC performance data, 2025-26",

    /* ---- what kind of office a partner is, in plain words ---- */
    "ptype.SCA": "State Scheduled Caste development corporation office",
    "ptype.PSB": "Public sector bank",
    "ptype.RRB": "Regional rural bank",
    "ptype.NBFC_MFI": "Micro-finance company",
    "ptype.COOP_BANK": "Co-operative bank",
    "ptype.COOP_SOCIETY": "Co-operative society",
    "ptype.SFB": "Small finance bank",
    "ptype.OTHER": "Another lender",

    /* ---- rules ---- */
    "rule.R_SC": "Scheduled Caste applicant",
    "rule.R_INCOME": "Annual family income limit",
    "rule.R_AMOUNT_MIN": "Smallest amount the scheme covers",
    "rule.R_AMOUNT_MAX": "Largest amount the scheme covers",
    "rule.R_COURSE": "Recognised course",
    "rule.R_DOCS": "Documents in hand",
    "rule.F_PURPOSE": "What the money is for",
    "rule.pass": "met",
    "rule.fail": "not met",
    "rule.skip": "not checked",

    /* ---- assistant ---- */
    "assistant.you": "You",
    "assistant.bot": "Sahaay",
    "assistant.thinking": "Reading the scheme pages…",
    "assistant.citation": "Source: {schemes} · nsfdc.nic.in",
    "assistant.error": "That question could not be answered right now.",
    "assistant.emptyQuestion": "Type a question first.",
    "mic.hold": "Hold to speak",
    "mic.listening": "Listening…",
    "mic.processing": "Working out what you said…",
    "mic.understood": "Understood — read it, and fix anything that is wrong:",
    "mic.denied": "The microphone was not allowed. You can still type your question.",
    "mic.unsupported": "This browser cannot record audio. You can still type your question.",
    "mic.tooShort": "That was too short to hear. Hold the button and speak again.",
    "mic.error": "The recording could not be sent. Try again, or type instead.",
    "mic.use": "Use this →",
    "mic.transcriptEmpty": "There is nothing in the box yet.",

    /* ---- wizard ---- */
    "wizard.progress": "Step {n} of {total}",
    "wizard.step1Title": "Tell us about yourself",
    "wizard.step1Help": "Speak in Hindi, or type. No sign-in needed.",
    "wizard.step2Title": "Is this right?",
    "wizard.step2Help": "Change anything we heard wrongly. Nothing is decided until you say so.",
    "wizard.step3Title": "Your match",
    "wizard.step4Title": "What it costs",
    "wizard.step5Title": "Which door",
    "wizard.step6Title": "Your packet",
    "wizard.textPlaceholder": "For example: I sew clothes in Bhopal and need one lakh twenty thousand for a machine.",
    "wizard.extract": "Continue",
    "wizard.extracting": "Reading what you wrote…",
    "wizard.extractError": "We could not read that. Try saying it again, in shorter sentences.",
    "wizard.emptyText": "Say or type something first.",
    "wizard.needAnswer": "Answer this before going on: {field}",
    "wizard.checklistTitle": "What to take with you",
    "wizard.nextStepsTitle": "What happens next",
    "wizard.pmSuraj": "Apply online at PM-SURAJ",
    "wizard.createProfile": "Want to be told when a new scheme matches you? Create a profile.",
    "wizard.packetError": "The packet could not be prepared.",

    /* ---- added for the Track B pages (00-CONTRACTS.md section 7) ---- */
    "brand.hi": "सहाय",
    "brand.ministry": "Ministry of Social Justice & Empowerment",
    "footer.prototype": "A prototype built for Smart India Hackathon 2026 · PS SIH26092",
    "footer.dept": "Ministry of Social Justice & Empowerment, Govt. of India",
    "hero.title_hi": "सही योजना। सही दफ़्तर। सही जानकारी।",
    "hero.title_en": "The right scheme. The right office. The right answer.",
    "hero.desc": "For Scheduled Caste entrepreneurs and students — find which NSFDC scheme fits you, what it will cost, and which office to walk into.",
    "hero.btn_wizard": "Find my scheme",
    "hero.btn_schemes": "Browse all schemes",
    "stats.enterprises": "SC-owned enterprises in India",
    "stats.reached": "reached by NSFDC last year",
    "stats.schemes": "schemes in one place",
    "stats.saved": "saved by choosing the right office",
    "stats.source": "Source: 6th Economic Census · NSFDC performance data, 2025-26",
    "how.title": "How it works",
    "how.step1_title": "Tell us about yourself",
    "how.step1_desc": "Type or speak in Hindi or English. No registration required to get started.",
    "how.step2_title": "We check every scheme",
    "how.step2_desc": "Checked against NSFDC's exact published eligibility criteria, not guesses.",
    "how.step3_title": "We tell you where to go",
    "how.step3_desc": "Routes you to the nearest state channel agency or partner office actively processing loans.",
    "usp.title": "What makes this different",
    "usp.no_title": "We explain a “no.”",
    "usp.no_desc": "Other portals show an empty list. We explain exact reasons: “Term Loan needs ₹1,40,001 — you asked for ₹1,20,000.”",
    "usp.door_title": "We tell you which door is open.",
    "usp.door_desc": "Fourteen State Channelizing Agencies are non-performing. We route you around them to active channels.",
    "usp.talk_title": "You can just talk.",
    "usp.talk_desc": "Voice input in Hindi/English. Built for accessibility since 89% of eligible applicants did not finish matriculation.",
    "login.heading": "Sign in",
    "login.subline": "You don't need an account to browse schemes or check eligibility. Sign in to save your profile and get told when a new scheme matches you.",
    "login.label_username": "Username",
    "login.label_password": "Password",
    "login.btn_submit": "Sign in",
    "login.demo_title": "Demo accounts:",
    "login.skip_link": "Continue without signing in →",
    "pf.heading": "Entrepreneur Profile",
    "pf.subline": "Keep your profile updated to see matching schemes automatically.",
    "pf.completion": "Profile complete: 8 of 11 fields",
    "pf.btn_upload_photo": "Upload a photo",
    "pf.sec_about": "About you",
    "pf.label_name": "Full Name",
    "pf.label_age": "Age",
    "pf.label_category": "Category",
    "pf.label_is_woman": "Female Applicant",
    "pf.sec_location": "Where you are",
    "pf.label_state": "State",
    "pf.label_district": "District",
    "pf.sec_contact": "Contact",
    "pf.label_email": "Email Address",
    "pf.label_mobile": "Mobile Number",
    "pf.sec_plan": "Your plan",
    "pf.label_purpose": "Purpose",
    "pf.label_sector": "Sector / Business Activity",
    "pf.label_amount": "Loan Amount Required (₹)",
    "pf.sec_finance": "Money & Education",
    "pf.label_income": "Annual Family Income (₹)",
    "pf.label_education": "Education Level",
    "pf.sec_docs": "Documents you have",
    "pf.label_caste_cert": "Caste Certificate Available",
    "pf.label_income_cert": "Income Certificate Available",
    "pf.btn_save": "Save Profile",
    "pf.notif_title": "Tell me about new schemes",
    "pf.notif_sub": "When a new scheme matches your profile, we will send you a message. (Preview — delivery is not connected in this prototype)",
    "filter.placeholder_search": "Search schemes by keyword or name...",
    "filter.cat_all": "All Categories",
    "filter.cat_loan": "Loans",
    "filter.cat_education": "Education",
    "filter.cat_subsidy": "Subsidy",
    "filter.cat_training": "Skill Training",
    "filter.cat_marketing": "Marketing Support",
    "filter.status_all": "All Statuses",
    "filter.status_open": "Open Only",
    "filter.status_closed": "Closed / Past",
    "scheme.btn_view": "View details →",
    "sc.label_rate": "Interest Rate",
    "sc.label_max": "Max Amount",
    "sc.label_period": "Repayment Period",
    "sc.label_moratorium": "Moratorium",
    "sc.heading_eligibility": "Who can apply (Eligibility)",
    "sc.heading_documents": "Documents to bring",
    "sc.heading_howto": "How to apply",
    "sc.check_title": "Wondering if this loan fits you?",
    "sc.check_desc": "We check your profile against NSFDC's official rules and show you exact repayment costs or specific reasons if you don't qualify.",
    "sc.btn_check": "Am I eligible?",
    "sc.source_line": "Terms as published at nsfdc.nic.in/scheme",
    "match.heading": "Your Scheme Matches",
    "match.top_sub": "The lowest interest rate you qualify for based on your project profile.",
    "match.heading_cost": "Exact Repayment Breakdown",
    "match.heading_nearmiss": "Schemes You Almost Qualified For",
    "match.heading_door": "Where to Apply (Functioning Partner Offices)",
    "match.heading_others": "Other Eligible Options",
    "match.wrongdoor_title": "Choosing the right office saves you ₹18,061",
    "match.wrongdoor_desc": "The exact same ₹1.2 lakh project costs 6.5% interest through the SC corporation (SCA) channel, but 15% through an NBFC-MFI channel — over the same 3 years.",
    "match.why_title": "Why this answer? (Click to expand evaluated rules)",
    "match.btn_print": "Print my packet",
    "match.btn_ask": "Ask a question →",
    "cost.instalment": "Quarterly Instalment",
    "cost.count": "Instalments",
    "cost.moratorium": "Moratorium",
    "cost.interest": "Total Interest",
    "cost.total": "Total Repayment",
    "partner.name": "Office / Channel Partner",
    "partner.type": "Type",
    "partner.rate": "Rate",
    "partner.status": "State Utilisation Status",
    "ast.heading": "Scheme AI Assistant",
    "ast.subline": "Ask questions about NSFDC schemes in plain Hindi or English. Answers are cited directly from official rules.",
    "ast.placeholder_input": "Type your question here...",
    "ast.btn_send": "Send",
    "ast.voice_title": "Voice Search (बोलकर पूछें)",
    "ast.voice_sub": "Hold the button, speak in Hindi or English, and verify your transcript.",
    "ast.mic_ready": "Click or hold microphone to record",
    "ast.label_transcript": "Editable Transcript:",
    "ast.placeholder_transcript": "Your spoken text will appear here. You can edit it before submitting...",
    "ast.btn_use_transcript": "Use this →",
    "wz.progress_title": "Scheme Eligibility Wizard",
    "wz.step1_title": "1. Tell us about your business or study plan",
    "wz.step1_sub": "Speak in Hindi or English, or type in the box below. No login required.",
    "wz.mic_prompt": "Click and hold to speak your requirements",
    "wz.label_type": "Or type your request:",
    "wz.placeholder_type": "e.g., Mujhe Bhopal me silai ke kaam ke liye 1.2 lakh ka loan chahiye...",
    "wz.btn_back": "← Back",
    "wz.btn_next": "Continue →",
    "wz.account_prompt": "Want to be told when a new scheme matches you?",
    "wz.link_create_profile": "Create a profile →",
  },

  hi: {
    /* ---- navigation ---- */
    "nav.brand": "सहाय",
    "nav.ministry": "सामाजिक न्याय और अधिकारिता मंत्रालय",
    "nav.home": "मुख्य पृष्ठ",
    "nav.schemes": "योजनाएँ",
    "nav.assistant": "सहायक",
    "nav.profile": "प्रोफ़ाइल",
    "nav.wizard": "मेरी योजना खोजें",
    "nav.match": "मेरे नतीजे",
    "nav.login": "साइन इन",
    "nav.logout": "साइन आउट",
    "nav.signedInAs": "{name} के रूप में साइन इन",

    /* ---- language ---- */
    "lang.toggle": "हिं | EN",
    "lang.switched": "भाषा हिंदी कर दी गई।",

    /* ---- shared ---- */
    "common.loading": "लोड हो रहा है…",
    "common.retry": "फिर कोशिश करें",
    "common.save": "सहेजें",
    "common.saving": "सहेजा जा रहा है…",
    "common.saved": "सहेज लिया गया।",
    "common.back": "पीछे",
    "common.next": "आगे",
    "common.finish": "पूरा करें",
    "common.print": "छापें",
    "common.view": "विवरण देखें",
    "common.na": "उपलब्ध नहीं",
    "common.yes": "हाँ",
    "common.no": "नहीं",
    "common.months": "{n} महीने",
    "common.percent": "{n}%",
    "common.source": "शर्तें nsfdc.nic.in/scheme पर प्रकाशित के अनुसार",

    /* ---- errors ---- */
    "err.network": "सर्वर तक नहीं पहुँच सके। देखें कि वह चल रहा है, फिर कोशिश करें।",
    "err.server": "सर्वर इस अनुरोध का जवाब नहीं दे सका।",
    "err.auth": "कृपया फिर से साइन इन करें।",
    "err.notfound": "यह नहीं मिला।",
    "err.unknown": "कुछ काम नहीं आया। फिर कोशिश करें।",

    /* ---- login ---- */
    "login.submit": "साइन इन",
    "login.submitting": "साइन इन हो रहा है…",
    "login.errorInvalid": "यह उपयोगकर्ता नाम और पासवर्ड मेल नहीं खाए। sunita / demo123 आज़माएँ।",
    "login.errorNetwork": "सर्वर तक नहीं पहुँच सके। देखें कि वह चल रहा है, फिर कोशिश करें।",
    "login.welcome": "{name} के रूप में साइन इन।",

    /* ---- profile ---- */
    "profile.loadError": "आपकी सहेजी हुई प्रोफ़ाइल नहीं खुल सकी।",
    "profile.saved": "सहेज लिया गया।",
    "profile.saveError": "आपकी प्रोफ़ाइल सहेजी नहीं जा सकी।",
    "profile.completeness": "प्रोफ़ाइल पूरी: {total} में से {done} जानकारी",
    "profile.photoUploading": "फ़ोटो भेजी जा रही है…",
    "profile.photoError": "फ़ोटो भेजी नहीं जा सकी।",
    "profile.seeMatches": "मेरे नतीजे देखें →",
    "profile.notifyUnavailable": "संदेश का नमूना अभी उपलब्ध नहीं है।",
    "profile.notifyTo": "{channel} से {to} पर भेजा जाता",
    "profile.needLogin": "प्रोफ़ाइल सहेजने के लिए साइन इन करें।",

    /* ---- field names: profile, wizard, why-panel ---- */
    "field.name": "नाम",
    "field.age": "उम्र",
    "field.is_sc": "अनुसूचित जाति",
    "field.category": "श्रेणी",
    "field.is_woman": "महिला",
    "field.state": "राज्य",
    "field.district": "ज़िला",
    "field.email": "ईमेल",
    "field.mobile": "मोबाइल नंबर",
    "field.purpose": "पैसा किस काम के लिए",
    "field.sector": "किस तरह का काम",
    "field.activity_text": "अपने शब्दों में",
    "field.amount_inr": "कितनी रकम चाहिए",
    "field.annual_family_income_inr": "परिवार की सालाना आय",
    "field.education": "पढ़ाई",
    "field.has_caste_certificate": "जाति प्रमाणपत्र",
    "field.has_income_certificate": "आय प्रमाणपत्र",
    "field.photo": "फ़ोटो",

    /* ---- option labels ---- */
    "category.sc": "अनुसूचित जाति",
    "category.st": "अनुसूचित जनजाति",
    "category.obc": "अन्य पिछड़ा वर्ग",
    "category.general": "सामान्य",
    "purpose.enterprise": "कोई काम-धंधा",
    "purpose.education": "पढ़ाई",
    "sector.tailoring": "सिलाई",
    "sector.shop": "दुकान",
    "sector.transport": "परिवहन",
    "sector.agri_allied": "खेती और उससे जुड़ा काम",
    "sector.services": "सेवाएँ",
    "sector.manufacturing": "निर्माण-उद्योग",
    "sector.plantation": "बागान",
    "sector.construction": "भवन-निर्माण",
    "sector.other": "कुछ और",
    "education.illiterate": "स्कूल नहीं गए",
    "education.primary": "प्राथमिक",
    "education.middle": "आठवीं",
    "education.matric": "दसवीं",
    "education.higher_secondary": "बारहवीं",
    "education.graduate": "स्नातक",

    /* ---- catalogue ---- */
    "schemes.count": "{total} में से {shown} दिख रही हैं",
    "schemes.empty": "इस खोज से कोई योजना नहीं मिली।",
    "schemes.loadError": "योजनाओं की सूची नहीं खुल सकी।",
    "schemes.filterAll": "सभी",
    "schemes.max": "अधिकतम {amount}",
    "schemes.closedNote": "नए आवेदनों के लिए बंद",
    "cat.loan": "ऋण",
    "cat.education": "शिक्षा",
    "cat.subsidy": "सब्सिडी",
    "cat.training": "प्रशिक्षण",
    "cat.marketing": "विपणन",
    "status.open": "खुली",
    "status.informational": "केवल जानकारी",
    "status.closed": "नए आवेदनों के लिए बंद",

    /* ---- one scheme ---- */
    "scheme.loadError": "यह योजना नहीं खुल सकी।",
    "scheme.notFound": "पते में कोई योजना नहीं बताई गई।",
    "scheme.check": "क्या मैं पात्र हूँ?",
    "scheme.checking": "प्रकाशित नियमों से जाँचा जा रहा है…",
    "scheme.checkYes": "हाँ — आप {scheme} के लिए पात्र हैं।",
    "scheme.checkYesCost": "{rate} · ऋण {loan} · किस्त {instalment}, कुल {count} किस्तें",
    "scheme.checkNo": "अभी नहीं — {reason}",
    "scheme.checkNoUnblock": "इससे बात बन जाएगी: {unblock}",
    "scheme.checkIneligible": "आपकी सहेजी हुई प्रोफ़ाइल इस योजना के लिए पात्र नहीं है।",
    "scheme.checkInfoOnly": "इस योजना की जानकारी हमारे पास है, पर जाँचने के नियम नहीं।",
    "scheme.checkNeedProfile": "छह सवालों के जवाब दीजिए, हम आपके लिए जाँच देंगे।",
    "scheme.checkError": "जाँच नहीं हो सकी।",
    "scheme.rateLabel": "ब्याज दर",
    "scheme.maxLabel": "अधिकतम रकम",
    "scheme.tenureLabel": "चुकाने की अवधि",
    "scheme.moratoriumLabel": "मोहलत",

    /* ---- matches ---- */
    "match.needProfile": "पहले आपकी जानकारी चाहिए।",
    "match.loading": "आपकी जानकारी से हर योजना जाँची जा रही है…",
    "match.error": "आपके नतीजे नहीं निकाले जा सके।",
    "match.none": "इस जानकारी से अभी कोई योजना नहीं बैठती।",
    "match.topTitle": "आपकी योजना: {scheme}",
    "match.rateLine": "{rate} — सबसे कम दर जिसके आप पात्र हैं",
    "match.otherRateLine": "{rate} ब्याज",
    "match.loanLine": "{project} के काम पर ऋण {loan} · आपका हिस्सा {own}",
    "match.costTitle": "कितना लगेगा",
    "match.costInstalment": "किस्त",
    "match.costCount": "किस्तों की संख्या",
    "match.costMoratorium": "मोहलत",
    "match.costTotalInterest": "कुल ब्याज",
    "match.costTotalRepayment": "कुल वापसी",
    "match.costRate": "ब्याज दर",
    "match.freq.quarterly": "हर तिमाही",
    "match.freq.half_yearly": "हर छह महीने",
    "match.nearmissTitle": "पास है, पर अभी नहीं",
    "match.nearmissNotYet": "{scheme} — अभी नहीं",
    "match.othersTitle": "ये भी आपके लिए खुली हैं",
    "match.doorTitle": "कहाँ जाना है",
    "match.doorNone": "आपके राज्य में इस योजना के लिए कोई दफ़्तर सूचीबद्ध नहीं है।",
    "match.doorDistance": "{km} किमी दूर",
    "match.doorDistanceUnknown": "दूरी पता नहीं",
    "match.doorRate": "आपके लिए {rate}",
    "match.wrongdoorTitle": "सही दफ़्तर चुनने से आपके {amount} बचते हैं",
    "match.wrongdoorBody": "यही काम {bestName} पर {bestRate} और {worstName} पर {worstRate} पड़ता है — उतनी ही अवधि में।",
    "match.whyTitle": "यह जवाब क्यों?",
    "match.whyLine": "{scheme} · {rule}: {result}",
    "match.whySaw": "हमने {value} पढ़ा",
    "match.whyNeeds": "नियम {threshold} माँगता है",
    "match.printPacket": "मेरा कागज़ छापें",
    "match.packetOpening": "आपके कागज़ तैयार हो रहे हैं…",
    "match.packetError": "कागज़ तैयार नहीं हो सके।",

    /* ---- utilisation bands ---- */
    "band.strong": "इस राज्य ने 2025-26 में अपना पूरा एनएसएफडीसी आवंटन इस्तेमाल किया।",
    "band.ok": "इस राज्य ने 2025-26 में अपना ज़्यादातर एनएसएफडीसी आवंटन इस्तेमाल किया।",
    "band.slow": "इस राज्य ने 2025-26 में अपने आवंटन का आधे से कम इस्तेमाल किया।",
    "band.weak": "इस राज्य ने 2025-26 में अपने आवंटन का बहुत थोड़ा हिस्सा इस्तेमाल किया।",
    "band.none": "इस राज्य के लिए कोई आँकड़ा प्रकाशित नहीं है।",
    "band.source": "एनएसएफडीसी प्रदर्शन आँकड़े, 2025-26",

    /* ---- what kind of office a partner is, in plain words ---- */
    "ptype.SCA": "अनुसूचित जाति विकास निगम का दफ़्तर",
    "ptype.PSB": "सरकारी बैंक",
    "ptype.RRB": "क्षेत्रीय ग्रामीण बैंक",
    "ptype.NBFC_MFI": "माइक्रो-फाइनेंस कंपनी",
    "ptype.COOP_BANK": "सहकारी बैंक",
    "ptype.COOP_SOCIETY": "सहकारी समिति",
    "ptype.SFB": "लघु वित्त बैंक",
    "ptype.OTHER": "कोई अन्य ऋणदाता",

    /* ---- rules ---- */
    "rule.R_SC": "अनुसूचित जाति का आवेदक",
    "rule.R_INCOME": "परिवार की सालाना आय की सीमा",
    "rule.R_AMOUNT_MIN": "योजना की सबसे छोटी रकम",
    "rule.R_AMOUNT_MAX": "योजना की सबसे बड़ी रकम",
    "rule.R_COURSE": "मान्यता प्राप्त पाठ्यक्रम",
    "rule.R_DOCS": "ज़रूरी कागज़ पास में",
    "rule.F_PURPOSE": "पैसा किस काम के लिए",
    "rule.pass": "पूरा हुआ",
    "rule.fail": "पूरा नहीं हुआ",
    "rule.skip": "जाँचा नहीं गया",

    /* ---- assistant ---- */
    "assistant.you": "आप",
    "assistant.bot": "सहाय",
    "assistant.thinking": "योजनाओं के पन्ने पढ़े जा रहे हैं…",
    "assistant.citation": "स्रोत: {schemes} · nsfdc.nic.in",
    "assistant.error": "इस सवाल का जवाब अभी नहीं मिल सका।",
    "assistant.emptyQuestion": "पहले कोई सवाल लिखिए।",
    "mic.hold": "बोलने के लिए दबाए रखें",
    "mic.listening": "सुन रहे हैं…",
    "mic.processing": "समझा जा रहा है कि आपने क्या कहा…",
    "mic.understood": "यह समझा — पढ़िए, और जो ग़लत हो उसे ठीक कीजिए:",
    "mic.denied": "माइक्रोफ़ोन की अनुमति नहीं मिली। आप लिखकर भी पूछ सकते हैं।",
    "mic.unsupported": "यह ब्राउज़र आवाज़ रिकॉर्ड नहीं कर सकता। आप लिखकर पूछ सकते हैं।",
    "mic.tooShort": "यह सुनने के लिए बहुत छोटा था। बटन दबाकर फिर बोलिए।",
    "mic.error": "रिकॉर्डिंग भेजी नहीं जा सकी। फिर कोशिश करें, या लिखकर बताएँ।",
    "mic.use": "यही आगे ले जाएँ →",
    "mic.transcriptEmpty": "अभी डिब्बे में कुछ नहीं है।",

    /* ---- wizard ---- */
    "wizard.progress": "चरण {n} / {total}",
    "wizard.step1Title": "अपने बारे में बताइए",
    "wizard.step1Help": "हिंदी में बोलिए, या लिखिए। साइन इन की ज़रूरत नहीं।",
    "wizard.step2Title": "क्या यह सही है?",
    "wizard.step2Help": "जो हमने ग़लत सुना, उसे बदल दीजिए। आपकी हामी से पहले कुछ तय नहीं होता।",
    "wizard.step3Title": "आपकी योजना",
    "wizard.step4Title": "कितना लगेगा",
    "wizard.step5Title": "कौन सा दफ़्तर",
    "wizard.step6Title": "आपके कागज़",
    "wizard.textPlaceholder": "जैसे: मैं भोपाल में सिलाई का काम करती हूँ, मशीन के लिए एक लाख बीस हज़ार चाहिए।",
    "wizard.extract": "आगे बढ़ें",
    "wizard.extracting": "जो आपने लिखा, वह पढ़ा जा रहा है…",
    "wizard.extractError": "हम इसे पढ़ नहीं सके। छोटे वाक्यों में फिर बताइए।",
    "wizard.emptyText": "पहले कुछ बोलिए या लिखिए।",
    "wizard.needAnswer": "आगे बढ़ने से पहले इसका जवाब दीजिए: {field}",
    "wizard.checklistTitle": "साथ क्या ले जाना है",
    "wizard.nextStepsTitle": "आगे क्या होगा",
    "wizard.pmSuraj": "पीएम-सूरज पर ऑनलाइन आवेदन",
    "wizard.createProfile": "नई योजना आपके लिए आए तो बताएँ? प्रोफ़ाइल बनाइए।",
    "wizard.packetError": "कागज़ तैयार नहीं हो सके।",

    /* ---- added for the Track B pages (00-CONTRACTS.md section 7) ---- */
    "brand.hi": "सहाय",
    "brand.ministry": "सामाजिक न्याय और अधिकारिता मंत्रालय",
    "footer.prototype": "स्मार्ट इंडिया हैकाथॉन 2026 के लिए बना एक प्रोटोटाइप · PS SIH26092",
    "footer.dept": "सामाजिक न्याय और अधिकारिता मंत्रालय, भारत सरकार",
    "hero.title_hi": "सही योजना। सही दफ़्तर। सही जानकारी।",
    "hero.title_en": "The right scheme. The right office. The right answer.",
    "hero.desc": "अनुसूचित जाति के उद्यमियों और विद्यार्थियों के लिए — जानिए कौन सी एनएसएफडीसी योजना आप पर लागू होती है, उसका खर्च कितना होगा, और किस दफ़्तर जाना है।",
    "hero.btn_wizard": "मेरी योजना खोजें",
    "hero.btn_schemes": "सभी योजनाएँ देखें",
    "stats.enterprises": "भारत में अनुसूचित जाति के स्वामित्व वाले उद्यम",
    "stats.reached": "पिछले वर्ष एनएसएफडीसी तक पहुँचे लोग",
    "stats.schemes": "योजनाएँ, एक ही जगह",
    "stats.saved": "सही दफ़्तर चुनने पर बचत",
    "stats.source": "स्रोत: छठी आर्थिक जनगणना · एनएसएफडीसी प्रदर्शन आँकड़े, 2025-26",
    "how.title": "यह कैसे काम करता है",
    "how.step1_title": "अपने बारे में बताइए",
    "how.step1_desc": "हिंदी या अंग्रेज़ी में लिखिए या बोलिए। शुरू करने के लिए किसी खाते की ज़रूरत नहीं।",
    "how.step2_title": "हम हर योजना जाँचते हैं",
    "how.step2_desc": "एनएसएफडीसी के प्रकाशित पात्रता नियमों से जाँच होती है, अंदाज़े से नहीं।",
    "how.step3_title": "हम बताते हैं कहाँ जाना है",
    "how.step3_desc": "आपको उस नज़दीकी राज्य चैनल एजेंसी या साझेदार दफ़्तर तक भेजते हैं जो सचमुच ऋण दे रहा है।",
    "usp.title": "यह अलग क्यों है",
    "usp.no_title": "हम “ना” की वजह बताते हैं।",
    "usp.no_desc": "दूसरे पोर्टल खाली सूची दिखाते हैं। हम सटीक कारण बताते हैं: “मियादी ऋण ₹1,40,001 से शुरू होती है — आपने ₹1,20,000 माँगे।”",
    "usp.door_title": "हम बताते हैं कौन सा दरवाज़ा खुला है।",
    "usp.door_desc": "चौदह राज्य चैनलाइज़िंग एजेंसियाँ काम नहीं कर रही हैं। हम आपको उनसे बचाकर चालू चैनल तक भेजते हैं।",
    "usp.talk_title": "आप बस बोल सकते हैं।",
    "usp.talk_desc": "हिंदी/अंग्रेज़ी में बोलकर बताइए। 89% पात्र आवेदक दसवीं पूरी नहीं कर पाए, इसीलिए यह सुविधा बनाई गई है।",
    "login.heading": "साइन इन करें",
    "login.subline": "योजनाएँ देखने या पात्रता जाँचने के लिए खाता ज़रूरी नहीं है। प्रोफ़ाइल सहेजने और नई योजना की सूचना पाने के लिए साइन इन कीजिए।",
    "login.label_username": "उपयोगकर्ता नाम",
    "login.label_password": "पासवर्ड",
    "login.btn_submit": "साइन इन करें",
    "login.demo_title": "डेमो खाते:",
    "login.skip_link": "बिना साइन इन के आगे बढ़ें →",
    "pf.heading": "उद्यमी प्रोफ़ाइल",
    "pf.subline": "प्रोफ़ाइल अद्यतन रखिए, ताकि आपके लिए उपयुक्त योजनाएँ अपने आप दिखें।",
    "pf.completion": "प्रोफ़ाइल पूरी: 11 में से 8 जानकारियाँ",
    "pf.btn_upload_photo": "फ़ोटो अपलोड कीजिए",
    "pf.sec_about": "आपके बारे में",
    "pf.label_name": "पूरा नाम",
    "pf.label_age": "उम्र",
    "pf.label_category": "वर्ग",
    "pf.label_is_woman": "महिला आवेदक",
    "pf.sec_location": "आप कहाँ हैं",
    "pf.label_state": "राज्य",
    "pf.label_district": "ज़िला",
    "pf.sec_contact": "संपर्क",
    "pf.label_email": "ईमेल पता",
    "pf.label_mobile": "मोबाइल नंबर",
    "pf.sec_plan": "आपकी योजना",
    "pf.label_purpose": "उद्देश्य",
    "pf.label_sector": "क्षेत्र / कारोबार",
    "pf.label_amount": "कितनी राशि चाहिए (₹)",
    "pf.sec_finance": "आय और शिक्षा",
    "pf.label_income": "वार्षिक पारिवारिक आय (₹)",
    "pf.label_education": "शिक्षा स्तर",
    "pf.sec_docs": "आपके पास मौजूद कागज़",
    "pf.label_caste_cert": "जाति प्रमाणपत्र उपलब्ध है",
    "pf.label_income_cert": "आय प्रमाणपत्र उपलब्ध है",
    "pf.btn_save": "प्रोफ़ाइल सहेजें",
    "pf.notif_title": "नई योजनाओं की सूचना दीजिए",
    "pf.notif_sub": "जब कोई नई योजना आपकी प्रोफ़ाइल से मेल खाएगी, हम संदेश भेजेंगे। (केवल झलक — इस प्रोटोटाइप में संदेश भेजना जुड़ा नहीं है)",
    "filter.placeholder_search": "नाम या शब्द से योजना खोजिए...",
    "filter.cat_all": "सभी श्रेणियाँ",
    "filter.cat_loan": "ऋण",
    "filter.cat_education": "शिक्षा",
    "filter.cat_subsidy": "सब्सिडी",
    "filter.cat_training": "कौशल प्रशिक्षण",
    "filter.cat_marketing": "विपणन सहायता",
    "filter.status_all": "सभी स्थितियाँ",
    "filter.status_open": "केवल खुली",
    "filter.status_closed": "बंद / पुरानी",
    "scheme.btn_view": "विवरण देखें →",
    "sc.label_rate": "ब्याज दर",
    "sc.label_max": "अधिकतम राशि",
    "sc.label_period": "चुकाने की अवधि",
    "sc.label_moratorium": "मोहलत",
    "sc.heading_eligibility": "कौन आवेदन कर सकता है (पात्रता)",
    "sc.heading_documents": "कौन से कागज़ ले जाने हैं",
    "sc.heading_howto": "आवेदन कैसे करें",
    "sc.check_title": "जानना चाहते हैं कि यह ऋण आपके लिए है?",
    "sc.check_desc": "हम आपकी जानकारी एनएसएफडीसी के आधिकारिक नियमों से जाँचते हैं और या तो सही खर्च बताते हैं, या पात्र न होने का सटीक कारण।",
    "sc.btn_check": "क्या मैं पात्र हूँ?",
    "sc.source_line": "शर्तें nsfdc.nic.in/scheme पर प्रकाशित रूप में",
    "match.heading": "आपके लिए उपयुक्त योजनाएँ",
    "match.top_sub": "आपकी जानकारी के आधार पर सबसे कम ब्याज दर जिसके आप पात्र हैं।",
    "match.heading_cost": "चुकाने का पूरा हिसाब",
    "match.heading_nearmiss": "जिन योजनाओं से आप थोड़ा चूक गए",
    "match.heading_door": "कहाँ आवेदन करें (चालू साझेदार दफ़्तर)",
    "match.heading_others": "अन्य विकल्प जिनके आप पात्र हैं",
    "match.wrongdoor_title": "सही दफ़्तर चुनने से आपके ₹18,061 बचते हैं",
    "match.wrongdoor_desc": "वही ₹1.2 लाख का काम एससी निगम (एससीए) के रास्ते 6.5% ब्याज पर पड़ता है, पर एनबीएफसी-एमएफआई के रास्ते 15% पर — उन्हीं 3 वर्षों में।",
    "match.why_title": "यह उत्तर क्यों? (जाँचे गए नियम देखने के लिए खोलिए)",
    "match.btn_print": "मेरे कागज़ छापें",
    "match.btn_ask": "सवाल पूछें →",
    "cost.instalment": "तिमाही किस्त",
    "cost.count": "कुल किस्तें",
    "cost.moratorium": "मोहलत",
    "cost.interest": "कुल ब्याज",
    "cost.total": "कुल भुगतान",
    "partner.name": "दफ़्तर / चैनल साझेदार",
    "partner.type": "प्रकार",
    "partner.rate": "दर",
    "partner.status": "राज्य के उपयोग की स्थिति",
    "ast.heading": "योजना सहायक",
    "ast.subline": "एनएसएफडीसी की योजनाओं के बारे में सरल हिंदी या अंग्रेज़ी में पूछिए। हर उत्तर आधिकारिक नियमों से लिया जाता है।",
    "ast.placeholder_input": "अपना सवाल यहाँ लिखिए...",
    "ast.btn_send": "भेजें",
    "ast.voice_title": "बोलकर पूछें",
    "ast.voice_sub": "बटन दबाए रखिए, हिंदी या अंग्रेज़ी में बोलिए, फिर लिखा हुआ जाँच लीजिए।",
    "ast.mic_ready": "रिकॉर्ड करने के लिए माइक दबाइए",
    "ast.label_transcript": "आप इसे सुधार सकते हैं:",
    "ast.placeholder_transcript": "आपकी बोली हुई बात यहाँ दिखेगी। भेजने से पहले आप उसे सुधार सकते हैं...",
    "ast.btn_use_transcript": "यही आगे भेजें →",
    "wz.progress_title": "योजना पात्रता सहायक",
    "wz.step1_title": "1. अपने काम या पढ़ाई की योजना बताइए",
    "wz.step1_sub": "हिंदी या अंग्रेज़ी में बोलिए, या नीचे लिखिए। साइन इन ज़रूरी नहीं।",
    "wz.mic_prompt": "बोलने के लिए दबाकर रखिए",
    "wz.label_type": "या अपनी बात लिखिए:",
    "wz.placeholder_type": "जैसे: मुझे भोपाल में सिलाई के काम के लिए 1.2 लाख का ऋण चाहिए...",
    "wz.btn_back": "← पीछे",
    "wz.btn_next": "आगे →",
    "wz.account_prompt": "नई योजना आपके लिए आए तो बताएँ?",
    "wz.link_create_profile": "प्रोफ़ाइल बनाइए →",
  }
};
